version: "3.8"
services:

  redis:
    image: redis:5.0-alpine
    ports:
      - "6379"
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=12345678
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: